[package]
name = "hyparview"
version = "0.1.0"
authors = ["Merlijn Boogerd <mboogerd@xebia.com>"]

[dependencies]
rand = "0.5.5"
actix = "0.7.4"
futures = "0.1.24"
futures-core = "0.2.1"
futures-channel = "0.2.1"